node {
    def mvnHome = tool name: 'Maven_3.8.6', type: 'maven'
    def jdkHome = tool name: 'JDK_17', type: 'jdk'

    env.PATH = "${jdkHome}\\bin;${mvnHome}\\bin;${env.PATH}"
    env.CATALINA_HOME = 'D:\\DevopsTaining\\All softwares\\apache-tomcat-9.0.104\\apache-tomcat-9.0.104'

    stage('Build WAR') {
        // You're already in the right directory with pom.xml
        bat 'mvn clean package'
    }node {
    def mvnHome = tool name: 'Maven_3.8.6', type: 'maven'
    def jdkHome = tool name: 'JDK_17', type: 'jdk'

    env.PATH = "${jdkHome}\\bin;${mvnHome}\\bin;${env.PATH}"
    env.CATALINA_HOME = 'D:\\DevopsTaining\\All softwares\\apache-tomcat-9.0.104\\apache-tomcat-9.0.104'

    stage('Checkout') {
        // Ensure the Git repository is checked out
        checkout scm
    }

    stage('Build WAR') {
        // Ensure Maven runs in the correct directory (root of the project where pom.xml is)
        dir('C:/ProgramData/Jenkins/.jenkins/workspace/ScriptedWebapp') {
            bat 'mvn clean package'
        }
    }

    stage('Deploy WAR Manually') {
        // Ensure the WAR file is copied to Tomcat's webapps folder
        bat 'echo Current directory: %CD%'
        bat 'dir target'
        bat 'if exist "%CATALINA_HOME%\\webapps\\" (echo Path exists) else (echo Path does NOT exist)'
        bat 'copy target\\ScriptedWebapp.war "%CATALINA_HOME%\\webapps\\"'
    }
}


    stage('Deploy WAR Manually') {
        // Just deploy the war from /target to Tomcat
        bat 'echo Current directory: %CD%'
        bat 'dir target'
        bat 'if exist "%CATALINA_HOME%\\webapps\\" (echo Path exists) else (echo Path does NOT exist)'
        bat 'copy target\\ScriptedWebapp.war "%CATALINA_HOME%\\webapps\\"'
    }
}
